Repository apache/arrow-java, pull requests merged in 2025-03, with the labels that each got.

#650 MINOR: Upgrade to GitHub actions/cache 4.2.2
  .github/workflows/dev.yml
  .github/workflows/rc.yml
  .github/workflows/test.yml
Labels: chore, enhancement

#649 MINOR: Add explicit exception when no more buffer can be read when loading buffers
  vector/src/main/java/org/apache/arrow/vector/VectorLoader.java
Labels: enhancement

#637 MINOR: Upgrade to Spotless 2.44.3 and Google Java Format 1.17 (supporting JDK23)
  adapter/avro/src/main/java/org/apache/arrow/adapter/avro/AvroToArrowConfig.java
  adapter/avro/src/main/java/org/apache/arrow/adapter/avro/AvroToArrowUtils.java
  adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcParameterBinder.java
  adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java
  adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowUtils.java
  adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/JdbcParameterBinderTest.java
  adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/UnreliableMetaDataTest.java
  bom/pom.xml
  c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java
  c/src/test/java/org/apache/arrow/c/StreamTest.java
  compression/src/main/java/org/apache/arrow/compression/Lz4CompressionCodec.java
  compression/src/main/java/org/apache/arrow/compression/ZstdCompressionCodec.java
  compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java
  flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java
  flight/flight-core/src/test/java/org/apache/arrow/flight/TestBasicOperation.java
  flight/flight-core/src/test/java/org/apache/arrow/flight/TestLargeMessage.java
  memory/memory-core/src/main/java/org/apache/arrow/memory/AllocationManager.java
  memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java
  memory/memory-core/src/main/java/org/apache/arrow/memory/BufferAllocator.java
  memory/memory-core/src/main/java/org/apache/arrow/memory/util/MemoryUtil.java
  memory/memory-core/src/main/java/org/apache/arrow/util/AutoCloseables.java
  pom.xml
  vector/src/main/java/org/apache/arrow/vector/Decimal256Vector.java
  vector/src/main/java/org/apache/arrow/vector/compare/VectorVisitor.java
  vector/src/main/java/org/apache/arrow/vector/dictionary/ListSubfieldEncoder.java
  vector/src/main/java/org/apache/arrow/vector/dictionary/StructSubfieldEncoder.java
  vector/src/main/java/org/apache/arrow/vector/table/Row.java
  vector/src/test/java/org/apache/arrow/vector/TestDenseUnionVector.java
  vector/src/test/java/org/apache/arrow/vector/TestDictionaryVector.java
  vector/src/test/java/org/apache/arrow/vector/TestFixedSizeListVector.java
  vector/src/test/java/org/apache/arrow/vector/TestIntervalMonthDayNanoVector.java
  vector/src/test/java/org/apache/arrow/vector/TestUnionVector.java
  vector/src/test/java/org/apache/arrow/vector/TestVectorSchemaRoot.java
  vector/src/test/java/org/apache/arrow/vector/ipc/MessageSerializerTest.java
  vector/src/test/java/org/apache/arrow/vector/ipc/TestArrowReaderWriter.java
Labels: dependencies

#652 MINOR: Update versions in LICENSE/NOTICE
  flight/flight-integration-tests/src/shade/LICENSE.txt
  flight/flight-integration-tests/src/shade/NOTICE.txt
  flight/flight-sql-jdbc-driver/src/shade/LICENSE.txt
  flight/flight-sql-jdbc-driver/src/shade/NOTICE.txt
  tools/src/shade/LICENSE.txt
  tools/src/shade/NOTICE.txt
  vector/src/shade/LICENSE.txt
Labels: enhancement

#660 GH-81: [Flight] Expose gRPC in Flight client builder
  flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java
  flight/flight-core/src/main/java/org/apache/arrow/flight/FlightGrpcUtils.java
  flight/flight-core/src/main/java/org/apache/arrow/flight/grpc/NettyClientBuilder.java
Labels: enhancement

#659 GH-456: Add action to assign milestone to PR/issue
  .github/workflows/dev_pr.yml
  .github/workflows/dev_pr_milestone.sh
Labels: chore

#670 MINOR: Add check-shebang-scripts-are-executable
  .github/workflows/dev_pr_milestone.sh
  .pre-commit-config.yaml
Labels: chore

#672 MINOR: Use mockito bom and upgrade to Mockito 5.16.0
  flight/flight-sql-jdbc-core/pom.xml
  pom.xml
Labels: dependencies, enhancement

#656 GH-655: Failure in UnionReader.read after DecimalVector promotion to UnionVector
  vector/src/main/codegen/templates/UnionVector.java
  vector/src/test/java/org/apache/arrow/vector/complex/impl/TestPromotableWriter.java
Labels: bug-fix

#681 MINOR: Upgrade to Apache POM 34
  pom.xml
Labels: dependencies

#689 MINOR: Fix macOS JNI build
  ci/scripts/jni_macos_build.sh
Labels: chore
