Repository apache/arrow-java, pull requests merged in 2025-05, with the labels that each got.

#727 GH-737: [FlightSQL] Allow returning column remarks in FlightSQL's CommandGetTables
  arrow-format/FlightSql.proto
  flight/flight-integration-tests/src/main/java/org/apache/arrow/flight/integration/tests/FlightSqlScenarioProducer.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowDatabaseMetadata.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ConvertUtils.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowDatabaseMetadataTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/ConvertUtilsTest.java
  flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlColumnMetadata.java
Labels: enhancement

#740 MINOR: Revert "MINOR: Bump io.netty:netty-bom from 4.1.119.Final to 4.2.0.Final (#700)"
  pom.xml
Labels: dependencies

#739 MINOR: Update third party versions in LICENSE and NOTICE
  flight/flight-integration-tests/src/shade/LICENSE.txt
  flight/flight-sql-jdbc-driver/src/shade/LICENSE.txt
Labels: dependencies

#662 GH-661: [Flight] JDBC: Cache failed locations
  flight/flight-sql-jdbc-core/pom.xml
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightConnection.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/utils/FlightClientCache.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/utils/FlightLocationQueue.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImpl.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ResultSetTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandlerBuilderTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/utils/FlightClientCacheTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/utils/FlightLocationQueueTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImplTest.java
Labels: enhancement

#741 MINOR: Bump version to 18.3.0
  adapter/avro/pom.xml
  adapter/jdbc/pom.xml
  adapter/orc/pom.xml
  algorithm/pom.xml
  bom/pom.xml
  c/pom.xml
  compression/pom.xml
  dataset/pom.xml
  flight/flight-core/pom.xml
  flight/flight-integration-tests/pom.xml
  flight/flight-sql-jdbc-core/pom.xml
  flight/flight-sql-jdbc-driver/pom.xml
  flight/flight-sql/pom.xml
  flight/pom.xml
  format/pom.xml
  gandiva/pom.xml
  memory/memory-core/pom.xml
  memory/memory-netty-buffer-patch/pom.xml
  memory/memory-netty/pom.xml
  memory/memory-unsafe/pom.xml
  memory/pom.xml
  performance/pom.xml
  pom.xml
  tools/pom.xml
  vector/pom.xml
Labels: chore

#754 MINOR: Bump version to 19.0.0-SNAPSHOT
  adapter/avro/pom.xml
  adapter/jdbc/pom.xml
  adapter/orc/pom.xml
  algorithm/pom.xml
  bom/pom.xml
  c/pom.xml
  compression/pom.xml
  dataset/pom.xml
  flight/flight-core/pom.xml
  flight/flight-integration-tests/pom.xml
  flight/flight-sql-jdbc-core/pom.xml
  flight/flight-sql-jdbc-driver/pom.xml
  flight/flight-sql/pom.xml
  flight/pom.xml
  format/pom.xml
  gandiva/pom.xml
  memory/memory-core/pom.xml
  memory/memory-netty-buffer-patch/pom.xml
  memory/memory-netty/pom.xml
  memory/memory-unsafe/pom.xml
  memory/pom.xml
  performance/pom.xml
  pom.xml
  tools/pom.xml
  vector/pom.xml
Labels: chore

#755 MINOR: add missing SOURCE_DIR in dev/release/release.sh
  dev/release/release.sh
Labels: bug-fix

#742 MINOR: Empty stream double check
  flight/flight-core/src/main/java/org/apache/arrow/flight/ArrowMessage.java
Labels: bug-fix

#761 GH-52: Make RangeEqualsVisitor of RunEndEncodedVector more efficient
  vector/src/main/java/org/apache/arrow/vector/compare/RangeEqualsVisitor.java
  vector/src/main/java/org/apache/arrow/vector/complex/RunEndEncodedVector.java
  vector/src/test/java/org/apache/arrow/vector/TestRunEndEncodedVector.java
  vector/src/test/java/org/apache/arrow/vector/compare/TestRangeEqualsVisitor.java
Labels: enhancement

#769 GH-768: Use apache/arrow-js for JS in integration test
  .github/workflows/test.yml
Labels: chore

#771 GH-770: Ensure updating Homebrew Python on macos-13
  .github/workflows/rc.yml
Labels: chore

#772 GH-70: Move from `hamcrest` to `assertj` in `flight-sql`
  flight/flight-sql/pom.xml
  flight/flight-sql/src/test/java/org/apache/arrow/flight/sql/test/TestFlightSql.java
  flight/flight-sql/src/test/java/org/apache/arrow/flight/sql/test/TestFlightSqlStateless.java
  flight/flight-sql/src/test/java/org/apache/arrow/flight/sql/test/TestFlightSqlStreams.java
Labels: chore
