Repository apache/arrow-java, pull requests merged in 2025-04, with the labels that each got.

#706 MINOR: Fix JNI code after upstream DCHECK change
  .github/workflows/rc.yml
  dataset/src/main/cpp/jni_util.cc
  gandiva/src/main/cpp/expression_registry_helper.cc
  gandiva/src/main/cpp/jni_common.cc
Labels: chore

#705 GH-704: Fix initialization of offset buffer when exporting VarChar vectors through C Data Interface
  c/src/test/java/org/apache/arrow/c/RoundtripTest.java
  vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java
  vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java
Labels: bug-fix

#495 GH-494: [Flight] Allow configuring connect timeout in JDBC
  flight/flight-sql-jdbc-core/pom.xml
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightConnection.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImpl.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ResultSetTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandlerBuilderTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImplTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/FallbackFlightSqlProducer.java
Labels: enhancement

#710 GH-708: Enable GitHub discussions
  .asf.yaml
Labels: chore

#707 GH-709: Correct length calculation of value buffers of variable-sized arrays
  c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java
Labels: bug-fix

#711 MINOR: Don't uninstall Flatbuffers in CI
  .github/workflows/rc.yml
  ci/scripts/jni_macos_build.sh
  ci/scripts/jni_manylinux_build.sh
Labels: chore

#722 GH-721: Allow using 1GB+ data buffers in variable width vectors
  pom.xml
  vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java
  vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthViewVector.java
  vector/src/test/java/org/apache/arrow/vector/TestValueVector.java
  vector/src/test/java/org/apache/arrow/vector/TestVectorReAlloc.java
  vector/src/test/java/org/apache/arrow/vector/util/TestVectorAppender.java
Labels: bug-fix

#724 GH-587: [Release] Add .env description to dev/release/README.md
  dev/release/.env.example
  dev/release/README.md
  dev/release/bump_version.sh
  dev/release/release.sh
  dev/release/release_rc.sh
Labels: documentation

#464 GH-463: Improve TZ support for JDBC driver
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcDateVectorAccessor.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcTimeStampVectorAccessor.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcTimeVectorAccessor.java
  flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/SqlTypes.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowDatabaseMetadataTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcTimeStampVectorAccessorTest.java
  flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/SqlTypesTest.java
Labels: bug-fix

#730 GH-729: [JDBC] Fix BinaryConsumer consuming null value
  adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/BinaryConsumer.java
  adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/consumer/BinaryConsumerTest.java
Labels: bug-fix
