Repository apache/arrow-java, pull requests merged in 2025-02, with the labels that each got.

#595 GH-55: [Gandiva] Re-enable tests
  .env
  .github/workflows/rc.yml
  compose.yaml
  gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/FilterProjectTest.java
  gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/FilterTest.java
  gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/ProjectorDecimalTest.java
  gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/ProjectorTest.java
Labels: bug-fix

#622 GH-620: Upgrade to Google flatbuffers 25.2.10
  format/src/main/java/org/apache/arrow/flatbuf/Binary.java
  format/src/main/java/org/apache/arrow/flatbuf/BinaryView.java
  format/src/main/java/org/apache/arrow/flatbuf/BodyCompression.java
  format/src/main/java/org/apache/arrow/flatbuf/Bool.java
  format/src/main/java/org/apache/arrow/flatbuf/Date.java
  format/src/main/java/org/apache/arrow/flatbuf/Decimal.java
  format/src/main/java/org/apache/arrow/flatbuf/DictionaryBatch.java
  format/src/main/java/org/apache/arrow/flatbuf/DictionaryEncoding.java
  format/src/main/java/org/apache/arrow/flatbuf/Duration.java
  format/src/main/java/org/apache/arrow/flatbuf/Field.java
  format/src/main/java/org/apache/arrow/flatbuf/FixedSizeBinary.java
  format/src/main/java/org/apache/arrow/flatbuf/FixedSizeList.java
  format/src/main/java/org/apache/arrow/flatbuf/FloatingPoint.java
  format/src/main/java/org/apache/arrow/flatbuf/Footer.java
  format/src/main/java/org/apache/arrow/flatbuf/Int.java
  format/src/main/java/org/apache/arrow/flatbuf/Interval.java
  format/src/main/java/org/apache/arrow/flatbuf/KeyValue.java
  format/src/main/java/org/apache/arrow/flatbuf/LargeBinary.java
  format/src/main/java/org/apache/arrow/flatbuf/LargeList.java
  format/src/main/java/org/apache/arrow/flatbuf/LargeListView.java
  format/src/main/java/org/apache/arrow/flatbuf/LargeUtf8.java
  format/src/main/java/org/apache/arrow/flatbuf/List.java
  format/src/main/java/org/apache/arrow/flatbuf/ListView.java
  format/src/main/java/org/apache/arrow/flatbuf/Map.java
  format/src/main/java/org/apache/arrow/flatbuf/Message.java
  format/src/main/java/org/apache/arrow/flatbuf/Null.java
  format/src/main/java/org/apache/arrow/flatbuf/RecordBatch.java
  format/src/main/java/org/apache/arrow/flatbuf/RunEndEncoded.java
  format/src/main/java/org/apache/arrow/flatbuf/Schema.java
  format/src/main/java/org/apache/arrow/flatbuf/SparseMatrixIndexCSX.java
  format/src/main/java/org/apache/arrow/flatbuf/SparseTensor.java
  format/src/main/java/org/apache/arrow/flatbuf/SparseTensorIndexCOO.java
  format/src/main/java/org/apache/arrow/flatbuf/SparseTensorIndexCSF.java
  format/src/main/java/org/apache/arrow/flatbuf/Struct_.java
  format/src/main/java/org/apache/arrow/flatbuf/Tensor.java
  format/src/main/java/org/apache/arrow/flatbuf/TensorDim.java
  format/src/main/java/org/apache/arrow/flatbuf/Time.java
  format/src/main/java/org/apache/arrow/flatbuf/Timestamp.java
  format/src/main/java/org/apache/arrow/flatbuf/Union.java
  format/src/main/java/org/apache/arrow/flatbuf/Utf8.java
  format/src/main/java/org/apache/arrow/flatbuf/Utf8View.java
  pom.xml
Labels: dependencies

#602 GH-601: [Gandiva] Synchronize some methods on the Projector
  gandiva/src/main/java/org/apache/arrow/gandiva/evaluator/Projector.java
Labels: bug-fix

#626 MINOR: Fix typo in dev_pr.js
  .github/workflows/dev_pr.js
Labels: github_actions, chore

#630 GH-629: Add post-release tasks to dev/release/README.md
  dev/release/README.md
Labels: documentation

#627 GH-625: Map MinorType getNewFieldWriter returns UnionMapWriter
  vector/src/main/java/org/apache/arrow/vector/types/Types.java
  vector/src/test/java/org/apache/arrow/vector/TestMapVector.java
Labels: bug-fix
